/**
 * WebApp Previewer Module for OpenCode
 * 
 * This module provides real-time preview functionality for web applications
 * generated by OpenCode. It automatically detects HTML files and displays
 * them in an embedded preview panel.
 */

export { WebAppPreviewer } from "./previewer"
export { useWebAppPreview } from "./use-webapp-preview"
export type { WebAppPreviewState, DeviceMode, DetectedFile, WebAppPreviewConfig } from "./types"
